apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: confluent

resources:
  - helmrepo.yaml
  - helmrelease.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: confluent-for-kuberentes-values
    files:
      - values.yaml