# rolebinding `testuser1-cfrb-kafka` allows `testuser1` to see kafka cluster
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: testuser1-cfrb-kafka
  namespace: operator
spec:
  principal:
    name: "/g1" # corresponding group from idp against testuser1
    type: group
  role: Operator
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: owner-operator-kafka
  namespace: operator
spec:
  principal:
    name: "/g4" # corresponding group from idp against testuser1
    type: group
  role: Operator
---

apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: sebastian-admin-kafka
  namespace: operator
spec:
  principal:
    name: "/g2" # corresponding group from idp against testuser1
    type: group
  role: ClusterAdmin
---

# rolebinding `testuser1-rb-connect` allows `testuser1` to see connect cluster
# `connectClusterId` pattern: `<namespace>.<connect.name>`
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: testuser1-rb-connect
  namespace: operator
spec:
  principal:
    name: "/g1" # corresponding sub from keycloak against testuser1
    type: group
  clustersScopeByIds:
    connectClusterId: operator.connect
  role: ClusterAdmin
  ## if use other kafkaRestClass except for default, need to configure accordingly
  #kafkaRestClassRef:
  # name: default
---
---
# rolebinding `testuser1-rb-sr` allows `testuser1` to see schemaregistry information
# `schemaRegistryCllusterId` pattern: `id_<schemaregistry.name>_<namespace>`
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: testuser1-rb-sr
  namespace: operator
spec:
  principal:
    name: "/g1" # corresponding sub from keycloak against testuser1
    type: group
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_operator
  role: SystemAdmin
---
# rolebinding `testuser1-rb-ksql` allows `testuser1` to see ksqldb cluster
# `ksqlClusterId` pattern: `<namespace>.<ksqldb.name>`
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: testuser1-rb-ksql
  namespace: operator
spec:
  principal:
    name: "/g1" # corresponding sub from keycloak against testuser1
    type: group
  clustersScopeByIds:
    ksqlClusterId: operator.ksqldb_
  role: ResourceOwner
  resourcePatterns:
    - name: ksql-cluster
      patternType: LITERAL
      resourceType: KsqlCluster
  ## if use other kafkaRestClass except for default, need to configure accordingly
  #kafkaRestClassRef:
  # name: default