apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: owner.resource-owner
  namespace: confluent
spec:
  principal:
    type: group
    name: "/g4"
  role: ResourceOwner
  resourcePatterns:
  - name: cloud.test.produce
    patternType: PREFIXED
    resourceType: Topic

---

apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: owner-user.resource-owner
  namespace: confluent
spec:
  principal:
    type: user
    name: 163ee8e8-04f8-4de2-ba22-daf394eea8f1
  role: ResourceOwner
  resourcePatterns:
  - name: cloud.test.produce
    patternType: PREFIXED
    resourceType: Topic
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: client.developer-write
  namespace: confluent
spec:
  principal:
    type: user
    name: a4e5acd5-c506-4100-909e-63a90199f398 # oauth-client
  role: DeveloperWrite
  resourcePatterns:
  - name: cloud.test.produce
    patternType: PREFIXED
    resourceType: Topic
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: client.developer-read
  namespace: confluent
spec:
  principal:
    type: user
    name: a4e5acd5-c506-4100-909e-63a90199f398 # oauth-client
  role: DeveloperRead
  resourcePatterns:
  - name: cloud.test.produce
    patternType: PREFIXED
    resourceType: Topic
  - name: client-
    patternType: PREFIXED
    resourceType: Group
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: ldap.developer-write
  namespace: confluent
spec:
  principal:
    type: group
    name: readonlyusers # ldap group
  role: DeveloperWrite
  resourcePatterns:
  - name: cloud.test.produce
    patternType: PREFIXED
    resourceType: Topic
  kafkaRestClassRef:
    name: default-ldap
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: ldap-user.developer-write
  namespace: confluent
spec:
  principal:
    type: user
    name: alice # ldap user
  role: DeveloperWrite
  resourcePatterns:
  - name: cloud.test.produce
    patternType: PREFIXED
    resourceType: Topic
  kafkaRestClassRef:
    name: default-ldap