apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: confluent
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kustomization/base/confluent/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
