apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
  namespace: confluent
spec:
  dataVolumeCapacity: 10G
  image:
    application: docker.io/confluentinc/cp-server:7.7.0
    init: confluentinc/confluent-init-container:2.9.1
  authorization:
    type: rbac
    superUsers:
      - User:e7121c1d-fe70-4828-a05b-0481e3304bab
      - User:kafka
  dependencies:
    mdsKafkaCluster:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9073
      authentication:
        type: oauth
        jaasConfig:
          secretRef: oauth-jass
        oauthSettings:
          tokenEndpointUri: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/oauth2/v2.0/token
          expectedIssuer: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/v2.0
          jwksEndpointUri: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/discovery/v2.0/keys
          scope: e7121c1d-fe70-4828-a05b-0481e3304bab/.default
  replicas: 1
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
    kafkaRest:
      authentication:
        type: oauth
        jaasConfig:
          secretRef: oauth-jass
        oauthSettings:
          tokenEndpointUri: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/oauth2/v2.0/token
          expectedIssuer: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/v2.0
          jwksEndpointUri: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/discovery/v2.0/keys
          scope: e7121c1d-fe70-4828-a05b-0481e3304bab/.default
  dataVolumeCapacity: 10G
  image:
    application: docker.io/confluentinc/cp-server:7.7.0
    init: confluentinc/confluent-init-container:2.9.1
  replicas: 3
  tls:
    autoGeneratedCerts: true
  listeners:
    external:
      authentication:
        type: oauth
        jaasConfig:
          secretRef: oauth-jass
        oauthSettings:
          groupsClaimName: groups
          subClaimName: sub
          audience: e7121c1d-fe70-4828-a05b-0481e3304bab
          expectedIssuer: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/v2.0
          jwksEndpointUri: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/discovery/v2.0/keys
          tokenEndpointUri: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/oauth2/v2.0/token
  authorization:
    type: rbac
    superUsers:
      - User:e7121c1d-fe70-4828-a05b-0481e3304bab
      - User:kafka
  services:
    mds:
      tls:
        enabled: true
      tokenKeyPair: 
        secretRef: mds-token
      provider:
        oauth:
          configurations:
            expectedIssuer: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/v2.0
            jwksEndpointUri: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/discovery/v2.0/keys
            tokenEndpointUri: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/oauth2/v2.0/token
        sso:
          enabled: true
          clientCredentials:
            secretRef: oauth-jass-oidc
          configurations:
            groupsClaimName: groups
            subClaimName: sub
            issuer: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/v2.0
            jwksEndpointUri: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/discovery/v2.0/keys
            authorizeBaseEndpointUri: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/oauth2/v2.0/authorize
            tokenBaseEndpointUri: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/oauth2/v2.0/token
            refreshToken: false
  configOverrides:
    server:
      - auto.create.topics.enable=true
      - listener.name.external.oauthbearer.sasl.server.callback.handler.class=org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerValidatorCallbackHandler
      - listener.name.external.oauthbearer.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: default
  namespace: confluent
spec:
  kafkaRest:
    authentication:
      type: oauth
      oauth:
        secretRef: oauth-jass
        configuration:
          tokenEndpointUri: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/oauth2/v2.0/token
          expectedIssuer: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/v2.0
          jwksEndpointUri: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/discovery/v2.0/keys
          scope: e7121c1d-fe70-4828-a05b-0481e3304bab/.default
---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.7.0
    init: confluentinc/confluent-init-container:2.9.1
  dataVolumeCapacity: 10Gi
  dependencies:
    kafka:
      bootstrapEndpoint: broker.confluent.svc.cluster.local:9092
      authentication:
        type: oauth
        jaasConfig:
          secretRef: oauth-jass
        oauthSettings:
          tokenEndpointUri: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/oauth2/v2.0/token
          scope: e7121c1d-fe70-4828-a05b-0481e3304bab/.default
    mds:
      ssoProtocol: oidc
      endpoint: https://kafka.confluent.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: oauth
        oauth:
          secretRef: oauth-jass
          configuration:
            tokenEndpointUri: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/oauth2/v2.0/token
            expectedIssuer: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/v2.0
            jwksEndpointUri: https://login.microsoftonline.com/6ee535f2-3064-4ac9-81d8-4ceb2ff790c6/discovery/v2.0/keys
            scope: e7121c1d-fe70-4828-a05b-0481e3304bab/.default
---