---
# Source: confluent-for-kubernetes/templates/serviceaccount.yaml
apiVersion: v1
imagePullSecrets:
- name: confluent-registry
kind: ServiceAccount
metadata:
  labels:
    app: confluent-for-kubernetes
    app.kubernetes.io/name: confluent-for-kubernetes
    app.kubernetes.io/instance: confluent-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "confluent-operator"
    helm.sh/chart: confluent-for-kubernetes-0.1193.1
  name: confluent-for-kubernetes
  namespace: confluent
---
# Source: confluent-for-kubernetes/templates/licensing.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: confluent-for-kubernetes
    app.kubernetes.io/name: confluent-for-kubernetes
    app.kubernetes.io/instance: confluent-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "confluent-operator"
    helm.sh/chart: confluent-for-kubernetes-0.1193.1
  namespace: confluent
  name: confluent-operator-licensing
type: Opaque
data:
---
# Source: confluent-for-kubernetes/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: confluent-for-kubernetes
    app.kubernetes.io/name: confluent-for-kubernetes
    app.kubernetes.io/instance: confluent-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "confluent-operator"
    helm.sh/chart: confluent-for-kubernetes-0.1193.1
  name: confluent-operator
  namespace: confluent
rules:
- apiGroups:
  - platform.confluent.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  - statefulsets/scale
  - statefulsets/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - persistentvolumes
  - secrets
  - secrets/finalizers
  - pods
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - ingresses/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
---
# Source: confluent-for-kubernetes/templates/clusterrolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: confluent-for-kubernetes
    app.kubernetes.io/name: confluent-for-kubernetes
    app.kubernetes.io/instance: confluent-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "confluent-operator"
    helm.sh/chart: confluent-for-kubernetes-0.1193.1
  name: confluent-operator
  namespace: confluent
subjects:
- kind: ServiceAccount
  name: confluent-for-kubernetes
  namespace: confluent
roleRef:
  kind: Role
  name: confluent-operator
  apiGroup: rbac.authorization.k8s.io
# Webhook configurations are cluster scoped
---
# Source: confluent-for-kubernetes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: confluent-for-kubernetes
    app.kubernetes.io/name: confluent-for-kubernetes
    app.kubernetes.io/instance: confluent-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "confluent-operator"
    helm.sh/chart: confluent-for-kubernetes-0.1193.1
  name: confluent-operator
  namespace:  confluent
spec:
  ports:
    - name: http-metric
      port: 7778
      protocol: TCP
      targetPort: 7778
  selector:
    app: "confluent-operator"
    app.kubernetes.io/name: "confluent-operator"
  type: ClusterIP
---
# Source: confluent-for-kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: confluent-for-kubernetes
    app.kubernetes.io/name: confluent-for-kubernetes
    app.kubernetes.io/instance: confluent-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "confluent-operator"
    helm.sh/chart: confluent-for-kubernetes-0.1193.1
    version: 0.1033.33
  name: confluent-operator
  namespace:  confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "confluent-operator"
      app.kubernetes.io/instance: confluent-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "7778"
        prometheus.io/scrape: "true"
      labels:
        app: "confluent-operator"
        app.kubernetes.io/name: "confluent-operator"
        app.kubernetes.io/instance: confluent-operator
        confluent-platform: "true"
        version: 0.1033.33
    spec:
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      containers:
      - args:
        - --debug=false
        - --fipsmode=false
        - --kraftClusterIdRecovery=false
        - --namespaces=confluent
        name: confluent-operator
        image: docker.io/confluentinc/confluent-operator:0.1033.33
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        readinessProbe:
          httpGet:
            port: 8080
            path: /readyz
        livenessProbe:
          httpGet:
            port: 8080
            path: /healthz
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODEIP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_ENTITY_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: DEPLOYMENT_NAME
            value: confluent-operator
          - name: CONFLUENT_SERVICE_ACCOUNT_NAME
            value: confluent-for-kubernetes
      serviceAccountName: confluent-for-kubernetes
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
